// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package com.scalabigdata.soap.wsdlconsumer

import scala.concurrent.Future

import com.scalabigdata.soap.wsdlconsumer



trait VV2_NOVOS_ENTRANTESMethodsSoap {
  def create(sessiontoken: String, bandeira: String, cpf_hash: String, origem: String, email: String, telefone_celular: String, opt_in_email: String, opt_in_sms: String): Future[String]
  def createCollection(sessiontoken: String): Future[wsdlconsumer.CreateCollectionResponse]
}




