// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package com.scalabigdata.wsdlconsumer

case class CalcPrecoPrazo(nCdEmpresa: Option[String] = None,
  sDsSenha: Option[String] = None,
  nCdServico: Option[String] = None,
  sCepOrigem: Option[String] = None,
  sCepDestino: Option[String] = None,
  nVlPeso: Option[String] = None,
  nCdFormato: Int,
  nVlComprimento: BigDecimal,
  nVlAltura: BigDecimal,
  nVlLargura: BigDecimal,
  nVlDiametro: BigDecimal,
  sCdMaoPropria: Option[String] = None,
  nVlValorDeclarado: BigDecimal,
  sCdAvisoRecebimento: Option[String] = None)
      


case class CalcPrecoPrazoResponse(CalcPrecoPrazoResult: wsdlconsumer.CResultado)
      


case class CResultado(Servicos: Option[wsdlconsumer.ArrayOfCServico] = None)
      


case class ArrayOfCServico(cServico: Seq[wsdlconsumer.CServico] = Nil)
      


case class CServico(Codigo: Int,
  Valor: Option[String] = None,
  PrazoEntrega: Option[String] = None,
  ValorMaoPropria: Option[String] = None,
  ValorAvisoRecebimento: Option[String] = None,
  ValorValorDeclarado: Option[String] = None,
  EntregaDomiciliar: Option[String] = None,
  EntregaSabado: Option[String] = None,
  Erro: Option[String] = None,
  MsgErro: Option[String] = None,
  ValorSemAdicionais: Option[String] = None,
  obsFim: Option[String] = None,
  DataMaxEntrega: Option[String] = None,
  HoraMaxEntrega: Option[String] = None)
      


case class CalcPrecoPrazoData(nCdEmpresa: Option[String] = None,
  sDsSenha: Option[String] = None,
  nCdServico: Option[String] = None,
  sCepOrigem: Option[String] = None,
  sCepDestino: Option[String] = None,
  nVlPeso: Option[String] = None,
  nCdFormato: Int,
  nVlComprimento: BigDecimal,
  nVlAltura: BigDecimal,
  nVlLargura: BigDecimal,
  nVlDiametro: BigDecimal,
  sCdMaoPropria: Option[String] = None,
  nVlValorDeclarado: BigDecimal,
  sCdAvisoRecebimento: Option[String] = None,
  sDtCalculo: Option[String] = None)
      


case class CalcPrecoPrazoDataResponse(CalcPrecoPrazoDataResult: wsdlconsumer.CResultado)
      


case class CalcPrecoPrazoRestricao(nCdEmpresa: Option[String] = None,
  sDsSenha: Option[String] = None,
  nCdServico: Option[String] = None,
  sCepOrigem: Option[String] = None,
  sCepDestino: Option[String] = None,
  nVlPeso: Option[String] = None,
  nCdFormato: Int,
  nVlComprimento: BigDecimal,
  nVlAltura: BigDecimal,
  nVlLargura: BigDecimal,
  nVlDiametro: BigDecimal,
  sCdMaoPropria: Option[String] = None,
  nVlValorDeclarado: BigDecimal,
  sCdAvisoRecebimento: Option[String] = None,
  sDtCalculo: Option[String] = None)
      


case class CalcPrecoPrazoRestricaoResponse(CalcPrecoPrazoRestricaoResult: wsdlconsumer.CResultado)
      


case class CalcPreco(nCdEmpresa: Option[String] = None,
  sDsSenha: Option[String] = None,
  nCdServico: Option[String] = None,
  sCepOrigem: Option[String] = None,
  sCepDestino: Option[String] = None,
  nVlPeso: Option[String] = None,
  nCdFormato: Int,
  nVlComprimento: BigDecimal,
  nVlAltura: BigDecimal,
  nVlLargura: BigDecimal,
  nVlDiametro: BigDecimal,
  sCdMaoPropria: Option[String] = None,
  nVlValorDeclarado: BigDecimal,
  sCdAvisoRecebimento: Option[String] = None)
      


case class CalcPrecoResponse(CalcPrecoResult: wsdlconsumer.CResultado)
      


case class CalcPrecoData(nCdEmpresa: Option[String] = None,
  sDsSenha: Option[String] = None,
  nCdServico: Option[String] = None,
  sCepOrigem: Option[String] = None,
  sCepDestino: Option[String] = None,
  nVlPeso: Option[String] = None,
  nCdFormato: Int,
  nVlComprimento: BigDecimal,
  nVlAltura: BigDecimal,
  nVlLargura: BigDecimal,
  nVlDiametro: BigDecimal,
  sCdMaoPropria: Option[String] = None,
  nVlValorDeclarado: BigDecimal,
  sCdAvisoRecebimento: Option[String] = None,
  sDtCalculo: Option[String] = None)
      


case class CalcPrecoDataResponse(CalcPrecoDataResult: wsdlconsumer.CResultado)
      


case class CalcPrazo(nCdServico: Option[String] = None,
  sCepOrigem: Option[String] = None,
  sCepDestino: Option[String] = None)
      


case class CalcPrazoResponse(CalcPrazoResult: wsdlconsumer.CResultado)
      


case class CalcPrazoData(nCdServico: Option[String] = None,
  sCepOrigem: Option[String] = None,
  sCepDestino: Option[String] = None,
  sDtCalculo: Option[String] = None)
      


case class CalcPrazoDataResponse(CalcPrazoDataResult: wsdlconsumer.CResultado)
      


case class CalcPrazoRestricao(nCdServico: Option[String] = None,
  sCepOrigem: Option[String] = None,
  sCepDestino: Option[String] = None,
  sDtCalculo: Option[String] = None)
      


case class CalcPrazoRestricaoResponse(CalcPrazoRestricaoResult: wsdlconsumer.CResultado)
      


case class CalcPrecoFAC(nCdServico: Option[String] = None,
  nVlPeso: Option[String] = None,
  strDataCalculo: Option[String] = None)
      


case class CalcPrecoFACResponse(CalcPrecoFACResult: wsdlconsumer.CResultado)
      


case class CalcDataMaxima(codigoObjeto: Option[String] = None)
      


case class CalcDataMaximaResponse(CalcDataMaximaResult: wsdlconsumer.CResultadoObjeto)
      


case class CResultadoObjeto(Objetos: Option[wsdlconsumer.ArrayOfCObjeto] = None)
      


case class ArrayOfCObjeto(cObjeto: Seq[wsdlconsumer.CObjeto] = Nil)
      


case class CObjeto(codigo: Option[String] = None,
  servico: Option[String] = None,
  cepOrigem: Option[String] = None,
  cepDestino: Option[String] = None,
  prazoEntrega: Int,
  dataPostagem: Option[String] = None,
  dataPostagemCalculo: Option[String] = None,
  dataMaxEntrega: Option[String] = None,
  postagemDH: Option[String] = None,
  dataUltimoEvento: Option[String] = None,
  codigoUltimoEvento: Option[String] = None,
  tipoUltimoEvento: Option[String] = None,
  descricaoUltimoEvento: Option[String] = None,
  erro: Option[String] = None,
  msgErro: Option[String] = None)
      


case class ListaServicos()
      


case class ListaServicosResponse(ListaServicosResult: wsdlconsumer.CResultadoServicos)
      


case class CResultadoServicos(ServicosCalculo: Option[wsdlconsumer.ArrayOfCServicosCalculo] = None)
      


case class ArrayOfCServicosCalculo(cServicosCalculo: Seq[wsdlconsumer.CServicosCalculo] = Nil)
      


case class CServicosCalculo(codigo: Option[String] = None,
  descricao: Option[String] = None,
  calcula_preco: Option[String] = None,
  calcula_prazo: Option[String] = None,
  erro: Option[String] = None,
  msgErro: Option[String] = None)
      

