// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package com.scalabigdata.wsdlconsumer

import scala.concurrent.Future


trait CalcPrecoPrazoWSSoap {
  def calcPrecoPrazo(nCdEmpresa: Option[String], sDsSenha: Option[String], nCdServico: Option[String], sCepOrigem: Option[String], sCepDestino: Option[String], nVlPeso: Option[String], nCdFormato: Int, nVlComprimento: BigDecimal, nVlAltura: BigDecimal, nVlLargura: BigDecimal, nVlDiametro: BigDecimal, sCdMaoPropria: Option[String], nVlValorDeclarado: BigDecimal, sCdAvisoRecebimento: Option[String]): Future[wsdlconsumer.CResultado]
  def calcPrecoPrazoData(nCdEmpresa: Option[String], sDsSenha: Option[String], nCdServico: Option[String], sCepOrigem: Option[String], sCepDestino: Option[String], nVlPeso: Option[String], nCdFormato: Int, nVlComprimento: BigDecimal, nVlAltura: BigDecimal, nVlLargura: BigDecimal, nVlDiametro: BigDecimal, sCdMaoPropria: Option[String], nVlValorDeclarado: BigDecimal, sCdAvisoRecebimento: Option[String], sDtCalculo: Option[String]): Future[wsdlconsumer.CResultado]
  def calcPrecoPrazoRestricao(nCdEmpresa: Option[String], sDsSenha: Option[String], nCdServico: Option[String], sCepOrigem: Option[String], sCepDestino: Option[String], nVlPeso: Option[String], nCdFormato: Int, nVlComprimento: BigDecimal, nVlAltura: BigDecimal, nVlLargura: BigDecimal, nVlDiametro: BigDecimal, sCdMaoPropria: Option[String], nVlValorDeclarado: BigDecimal, sCdAvisoRecebimento: Option[String], sDtCalculo: Option[String]): Future[wsdlconsumer.CResultado]
  def calcPreco(nCdEmpresa: Option[String], sDsSenha: Option[String], nCdServico: Option[String], sCepOrigem: Option[String], sCepDestino: Option[String], nVlPeso: Option[String], nCdFormato: Int, nVlComprimento: BigDecimal, nVlAltura: BigDecimal, nVlLargura: BigDecimal, nVlDiametro: BigDecimal, sCdMaoPropria: Option[String], nVlValorDeclarado: BigDecimal, sCdAvisoRecebimento: Option[String]): Future[wsdlconsumer.CResultado]
  def calcPrecoData(nCdEmpresa: Option[String], sDsSenha: Option[String], nCdServico: Option[String], sCepOrigem: Option[String], sCepDestino: Option[String], nVlPeso: Option[String], nCdFormato: Int, nVlComprimento: BigDecimal, nVlAltura: BigDecimal, nVlLargura: BigDecimal, nVlDiametro: BigDecimal, sCdMaoPropria: Option[String], nVlValorDeclarado: BigDecimal, sCdAvisoRecebimento: Option[String], sDtCalculo: Option[String]): Future[wsdlconsumer.CResultado]
  def calcPrazo(nCdServico: Option[String], sCepOrigem: Option[String], sCepDestino: Option[String]): Future[wsdlconsumer.CResultado]
  def calcPrazoData(nCdServico: Option[String], sCepOrigem: Option[String], sCepDestino: Option[String], sDtCalculo: Option[String]): Future[wsdlconsumer.CResultado]
  def calcPrazoRestricao(nCdServico: Option[String], sCepOrigem: Option[String], sCepDestino: Option[String], sDtCalculo: Option[String]): Future[wsdlconsumer.CResultado]
  def calcPrecoFAC(nCdServico: Option[String], nVlPeso: Option[String], strDataCalculo: Option[String]): Future[wsdlconsumer.CResultado]
  def calcDataMaxima(codigoObjeto: Option[String]): Future[wsdlconsumer.CResultadoObjeto]
  def listaServicos(): Future[wsdlconsumer.CResultadoServicos]
}




